name: culture_db_env
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - annotated-types==0.7.0
    - blinker==1.9.0
    - certifi==2024.12.14
    - charset-normalizer==3.4.1
    - click==8.1.8
    - dash==2.18.2
    - dash-bootstrap-components==1.7.1
    - dash-core-components==2.0.0
    - dash-cytoscape==1.0.2
    - dash-daq==0.5.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - flask<3.1
    - werkzeug<3.1
    - importlib_metadata
    - typing_extensions
    - zipp
    - plotly